INSERT INTO AUTHORITY (AUTHORITY_ID, AUTHORITY)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (AUTHORITY_ID, AUTHORITY)
VALUES (2, 'ROLE_USER');

INSERT INTO USER (USERNAME, PASSWORD, AUTHORITY_ID)
VALUES ('admin', '$2a$12$DyZcTJljvpxqbvQPeUptYuJtKMweFp8KGktVc7B9SHBCvEgmKsbrK',1);
INSERT INTO USER (USERNAME, PASSWORD, AUTHORITY_ID)
VALUES ('user2', '$2a$10$I.aQETJOwbu6Vwc/RZSVNuqKP4Pqe2GF6lNwpNWM3HB3OY6Stmyum', 2);